name: First CI/CD Pipeline # 工作流名称
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  build-job:
    runs-on: ubuntu-latest 
    steps:
      - name: Run build script
        run: echo "Hello, ${{ github.actor }}!"

  test-job1:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: Run test script
        run: echo "This job tests something"

  test-job2:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: Run longer test script
        run: |
          echo "This job tests something, but takes more time than test-job1."
          echo "After the echo commands complete, it runs the sleep command for 20 seconds"
          echo "which simulates a test that runs 20 seconds longer than test-job1"
          sleep 20

  deploy-prod:
    needs: [test-job1, test-job2] 
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy script
        run: echo "This job deploys something from the ${{ github.ref_name }} branch." # 输出当前分支名
